blank_issues_enabled: false
contact_links:
  - name: Preguntas y soporte
    url: https://github.com/ivan2214/Argentina-gasto-publico/issues
    about: Utiliza los issues para discutir mejoras o reportar problemas.
