name: Crear PR de develop a main

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Asegura que el PR ha sido fusionado
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Crear Pull Request de develop a main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Actualización automática desde develop'
          title: 'Merge automático: develop → main'
          body: 'Este PR se ha generado automáticamente tras el merge de una feature en develop, y se requiere su integración en main.'
          base: main
          branch: develop
