name: Validar Mensajes de Commit y Calidad del Código

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.1"

      - name: Instalar dependencias del sistema
        run: sudo apt-get update && sudo apt-get install -y curl bash

      - name: Instalar Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
        env:
          BUN_INSTALL: "$HOME/.bun"
          PATH: "$BUN_INSTALL/bin:$PATH"

      - name: Instalar dependencias
        run: |
          bun install
        env:
          BUN_INSTALL: "$HOME/.bun"
          PATH: "$BUN_INSTALL/bin:$PATH"

      - name: Ejecutar Biome
        run: |
          bun run check
        env:
          BUN_INSTALL: "$HOME/.bun"
          PATH: "$BUN_INSTALL/bin:$PATH"

      - name: Ejecutar Commitlint
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            npx commitlint --from=HEAD~1 --to=HEAD --verbose
          else
            echo "Solo un commit en el historial, omitiendo Commitlint."
          fi
