name: Validar Mensajes de Commit y Calidad del C贸digo

on:
  pull_request:
    branches:
      - main
      - develop # O cualquier rama en la que quieras aplicar la validaci贸n
  workflow_dispatch: # Esto permite ejecutar la acci贸n manualmente desde la interfaz de GitHub

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el c贸digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.1"

      - name: Instalar Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Instalar dependencias
        run: |
          bun install

      - name: Ejecutar Biome
        run: |
          bun run check

      - name: Ejecutar Commitlint
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            npx commitlint --from=HEAD~1 --to=HEAD --verbose
          else
            echo "Solo un commit en el historial, omitiendo Commitlint."
          fi
